[package]
name = "solana-kita-cache"
description = "Kita-Cache: Program JIT Cache v2"
documentation = "https://docs.rs/solana-kita-cache"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
agave-unstable-api = []
dev-context-only-utils = []

[dependencies]
solana-clock = { workspace = true }
solana-pubkey = { workspace = true }
solana-sbpf = { workspace = true, features = ["jit"] }
solana-svm-callback = { workspace = true }

[lints]
workspace = true
