[package]
name = "solana-sbf-rust-abi-v1-v2-cpi"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[features]
custom-heap = []
custom-panic = []

[dependencies]
solana-account-info = { workspace = true }
solana-program = { workspace = true }
solana-program-entrypoint = { workspace = true }
solana-pubkey = { workspace = true }

[lints]
workspace = true
