[package]
name = "solana-sbf-rust-abi-v2-memory"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[features]
dummy-for-ci-check = ["solana-transaction-context/dummy-for-ci-check"]

[dependencies]
bincode = { workspace = true }
solana-clock = { workspace = true }
solana-epoch-rewards = { workspace = true, features = ["serde"] }
solana-epoch-schedule = { workspace = true, features = ["serde"] }
solana-last-restart-slot = { workspace = true, features = ["serde"] }
solana-pubkey = { workspace = true }
solana-rent = { workspace = true, features = ["sysvar", "serde"] }
solana-slot-hashes = { workspace = true, features = ["serde"] }
solana-stake-history = { workspace = true, features = ["serde"] }
solana-transaction-context = { workspace = true, features = ["agave-unstable-api"] }
