[package]
name = "solana-svm-test-harness-syscall"
description = "Solana SVM test harness for syscalls."
documentation = "https://docs.rs/solana-svm-test-harness-syscall"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[features]
dummy-for-ci-check = []

[dependencies]

[lints]
workspace = true
