[package]
name = "solana-program-account"
description = "Program account ELF extraction"
documentation = "https://docs.rs/solana-program-account"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
solana-account = { workspace = true, features = ["bincode"] }
solana-loader-v3-interface = { workspace = true, features = ["bincode"] }
solana-loader-v4-interface = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk-ids = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }

[lints]
workspace = true
