[package]
name = "svm-type-overrides"
description = "SVM type overrides for testing (forked from solana-type-overrides)"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
shuttle-test = ["dep:shuttle"]
executor = ["dep:futures"]

[dependencies]
futures = { workspace = true, optional = true }
rand = { workspace = true }
shuttle = { workspace = true, optional = true }
