[package]
name = "solana-svm-fuzz-harness-vm"
description = "Solana SVM fuzz harness for VM."
documentation = "https://docs.rs/solana-svm-fuzz-harness-vm"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { version = "4.5.2", features = ["derive"] }
prost = { workspace = true }
solana-account = { workspace = true }
solana-bpf-loader-program = { workspace = true }
solana-compute-budget = { workspace = true }
solana-feature-set = { workspace = true }
solana-log-collector = { workspace = true }
solana-poseidon = { workspace = true }
solana-program-runtime = { workspace = true }
solana-pubkey = { workspace = true }
solana-rent = { workspace = true }
solana-svm-fuzz-harness-fixture = { workspace = true }
solana-svm-fuzz-harness-instr = { workspace = true }
# For crates not decoupled from SDK yet...
solana-sdk = { workspace = true }

[lints]
workspace = true
